version: "3"
services:
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  mysql:
    image: 'mysql:5.7'
    ports:
      - '6306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=nsoft
      - MYSQL_USER=nsoft
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=yellow
  yellow-backend:
    image: 'danielvasic1/yellow-backend:latest'
    ports:
      - '8080:8080'
    depends_on:
      - mysql
      - kafka
  kafka:
    image: 'wurstmeister/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper